version: "3"
services:
  statsd_exporter:
    image: prom/statsd-exporter
    ports:
      - "9102:9102"
      - "9125:9125/udp"

  prometheus:
    image: prom/prometheus
    command: "--config.file=/tmp/prometheus.yml --web.listen-address '0.0.0.0:9090'"
    ports:
      - "9090:9090"
    volumes:
      - "./prometheus.yml:/tmp/prometheus.yml"

  populator:
      user: root
      image: bash:4.0.44-alpine3.19
      volumes:
        - "./populate.sh:/tmp/populate.sh"
      command: "bash /tmp/populate.sh 2"
